spring:
  config:
    activate:
      on-profile: traffic
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.session.SessionAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.session.SessionsEndpointAutoConfiguration
  data:
    redis:
      repositories:
        enabled: false
  main:
    web-application-type: servlet
  session:
    store-type: none
  task:
    scheduling:
      enabled: true

management:
  endpoint:
    sessions:
      enabled: false

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

app:
  streams:
    consumer-enabled: true
