spring:
  config:
    activate:
      on-profile: api
  task:
    scheduling:
      enabled: false

app:
  streams:
    consumer-enabled: false
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "6"