DROP TABLE IF EXISTS `DAILY_APP_TOTAL_DATA`;

CREATE TABLE `DAILY_APP_TOTAL_DATA` (
	`usage_date`	DATE	NOT NULL	COMMENT 'UK',
	`line_id`	BIGINT	NOT NULL	COMMENT 'UK',
	`application_id`	INT	NOT NULL	COMMENT 'UK',
	`total_usage_data`	BIGINT	NOT NULL,
	`created_at`	TIMESTAMP	NOT NULL,
	`deleted_at`	TIMESTAMP	NULL,
	`updated_at`	TIMESTAMP	NULL
);

DROP TABLE IF EXISTS `QUESTION_CATEGORY`;

CREATE TABLE `QUESTION_CATEGORY` (
	`question_category_id`	INT	NOT NULL,
	`question_category_name`	VARCHAR(20)	NOT NULL	COMMENT 'uk',
	`created_at`	TIMESTAMP	NOT NULL,
	`deleted_at`	TIMESTAMP	NULL
);

DROP TABLE IF EXISTS `WHITELIST`;

CREATE TABLE `WHITELIST` (
	`whitelist_id`	BIGINT	NOT NULL,
	`line_id`	BIGINT	NOT NULL,
	`application_id`	INT	NOT NULL,
	`is_active`	BOOLEAN	NOT NULL,
	`created_at`	TIMESTAMP	NOT NULL,
	`deleted_at`	TIMESTAMP	NULL,
	`updated_at`	TIMESTAMP	NULL
);

DROP TABLE IF EXISTS `DAILY_LIMIT`;

CREATE TABLE `DAILY_LIMIT` (
	`daily_limit_id`	BIGINT	NOT NULL,
	`line_id`	BIGINT	NOT NULL,
	`daily_data_limit`	BIGINT	NOT NULL	COMMENT '단위 KB',
	`is_active`	BOOLEAN	NOT NULL,
	`created_at`	TIMESTAMP	NOT NULL,
	`deleted_at`	TIMESTAMP	NULL,
	`updated_at`	TIMESTAMP	NULL
);

DROP TABLE IF EXISTS `DAILY_TOTAL_DATA`;

CREATE TABLE `DAILY_TOTAL_DATA` (
	`usage_date`	DATE	NOT NULL	COMMENT 'UK',
	`line_id`	BIGINT	NOT NULL	COMMENT 'UK',
	`total_usage_data`	BIGINT	NOT NULL,
	`created_at`	TIMESTAMP	NOT NULL,
	`deleted_at`	TIMESTAMP	NULL,
	`updated_at`	TIMESTAMP	NULL
);

DROP TABLE IF EXISTS `REPEAT_BLOCK`;

CREATE TABLE `REPEAT_BLOCK` (
	`repeat_block_id`	BIGINT	NOT NULL,
	`line_id`	BIGINT	NOT NULL,
	`is_active`	BOOLEAN	NOT NULL	COMMENT '활성화 / 비활성화',
	`start_at`	INT	NOT NULL	COMMENT '24시 표기',
	`end_at`	INT	NOT NULL	COMMENT '24시 표기',
	`created_at`	TIMESTAMP	NOT NULL,
	`deleted_at`	TIMESTAMP	NULL,
	`updated_at`	TIMESTAMP	NULL
);

DROP TABLE IF EXISTS `FAMILY`;

CREATE TABLE `FAMILY` (
	`family_id`	BIGINT	NOT NULL,
	`pool_base_data`	BIGINT	NOT NULL	DEFAULT 0,
	`pool_total_data`	BIGINT	NOT NULL	DEFAULT 0,
	`pool_remaining_data`	BIGINT	NOT NULL	DEFAULT 0,
	`created_at`	TIMESTAMP	NOT NULL,
	`deleted_at`	TIMESTAMP	NULL,
	`updated_at`	TIMESTAMP	NULL,
	`family_threshold`	BIGINT	NOT NULL,
	`is_threshold_active`	BOOLEAN	NOT NULL	DEFAULT false
);

DROP TABLE IF EXISTS `PERMISSION`;

CREATE TABLE `PERMISSION` (
	`permission_id`	INT	NOT NULL,
	`permission_title`	VARCHAR(20)	NOT NULL,
	`created_at`	TIMESTAMP	NOT NULL,
	`deleted_at`	TIMESTAMP	NULL,
	`updated_at`	TIMESTAMP	NULL
);

DROP TABLE IF EXISTS `POLICY`;

CREATE TABLE `POLICY` (
	`policy_id`	INT	NOT NULL,
	`policy_category_id`	INT	NOT NULL,
	`policy_name`	VARCHAR(50)	NOT NULL,
	`is_active`	BOOLEAN	NOT NULL	DEFAULT FALSE,
	`is_new`	BOOLEAN	NOT NULL	DEFAULT TRUE,
	`created_at`	TIMESTAMP	NOT NULL,
	`deleted_at`	TIMESTAMP	NULL,
	`updated_at`	TIMESTAMP	NULL
);

DROP TABLE IF EXISTS `FAMILY_SHARED_USAGE_DAILY`;

CREATE TABLE `FAMILY_SHARED_USAGE_DAILY` (
	`usage_date`	DATE	NOT NULL,
	`family_id`	BIGINT	NOT NULL,
	`line_id`	BIGINT	NOT NULL,
	`usage_amount`	BIGINT	NOT NULL	DEFAULT 0,
	`contribution_amount`	BIGINT	NOT NULL	DEFAULT 0	COMMENT '회선에서 공유풀에 충전한 데이터량',
	`created_at`	TIMESTAMP	NOT NULL,
	`deleted_at`	TIMESTAMP	NULL,
	`updated_at`	TIMESTAMP	NULL
);

DROP TABLE IF EXISTS `LINE`;

CREATE TABLE `LINE` (
	`line_id`	BIGINT	NOT NULL,
	`user_id`	BIGINT	NOT NULL,
	`plan_id`	INT	NOT NULL,
	`phone`	VARCHAR(20)	NOT NULL	COMMENT 'UK',
	`block_end_at`	DATETIME	NULL,
	`remaining_data`	BIGINT	NOT NULL	DEFAULT 0,
	`is_main`	BOOLEAN	NOT NULL,
	`created_at`	TIMESTAMP	NOT NULL,
	`deleted_at`	TIMESTAMP	NULL,
	`updated_at`	TIMESTAMP	NULL,
	`individual_threshold`	BIGINT	NULL,
	`is_threshold_active`	BOOLEAN	NOT NULL	DEFAULT FALSE
);

DROP TABLE IF EXISTS `ROLE`;

CREATE TABLE `ROLE` (
	`role_id`	INT	NOT NULL,
	`role_name`	VARCHAR(10)	NOT NULL
);

DROP TABLE IF EXISTS `FAMILY_LINE`;

CREATE TABLE `FAMILY_LINE` (
	`family_id`	BIGINT	NOT NULL,
	`line_id`	BIGINT	NOT NULL,
	`role`	ENUM('OWNER', 'MEMBER')	NOT NULL	DEFAULT 'MEMBER'	COMMENT '(대표,구성원)',
	`is_public`	BOOLEAN	NOT NULL	DEFAULT true,
	`created_at`	TIMESTAMP	NOT NULL,
	`updated_at`	TIMESTAMP	NULL
);

DROP TABLE IF EXISTS `QUESTION`;

CREATE TABLE `QUESTION` (
	`question_id`	BIGINT	NOT NULL,
	`question_category_id`	INT	NOT NULL,
	`line_id`	BIGINT	NOT NULL,
	`title`	VARCHAR(50)	NOT NULL,
	`content`	VARCHAR(1000)	NOT NULL,
	`is_answer`	BOOLEAN	NOT NULL,
	`created_at`	TIMESTAMP	NOT NULL,
	`deleted_at`	TIMESTAMP	NULL
);

DROP TABLE IF EXISTS `Application`;

CREATE TABLE `Application` (
	`application_id`	INT	NOT NULL,
	`application_name`	VARCHAR(20)	NOT NULL,
	`category`	ENUM( 'SNS','ENTERTAINMENT','WEB','EDUCATION','SHOPPING','OTHER')	NOT NULL
);

DROP TABLE IF EXISTS `USERS`;

CREATE TABLE `USERS` (
	`user_id`	BIGINT	NOT NULL,
	`user_name`	VARCHAR(50)	NOT NULL,
	`email`	VARCHAR(50)	NOT NULL,
	`password`	VARCHAR(255)	NOT NULL,
	`age`	TINYINT	NOT NULL,
	`created_at`	TIMESTAMP	NOT NULL,
	`deleted_at`	TIMESTAMP	NULL,
	`updated_at`	TIMESTAMP	NULL
);

DROP TABLE IF EXISTS `PERMISSION_LINE`;

CREATE TABLE `PERMISSION_LINE` (
	`line_id`	BIGINT	NOT NULL	COMMENT 'UK',
	`permission_id`	INT	NOT NULL	COMMENT 'UK',
	`is_enable`	BOOLEAN	NOT NULL	DEFAULT FALSE,
	`created_at`	TIMESTAMP	NOT NULL,
	`updated_at`	TIMESTAMP	NULL
);

DROP TABLE IF EXISTS `ALRAM_HISTORY`;

CREATE TABLE `ALRAM_HISTORY` (
	`alarm_history_id`	BIGINT	NOT NULL,
	`user_id`	BIGINT	NOT NULL,
	`alarm_code`	ENUM('LIMIT','POLICY', 'PERMISSION','QUESTION')	NOT NULL	COMMENT 'enum',
	`value`	TEXT	NULL	COMMENT 'json',
	`created_at`	TIMESTAMP	NOT NULL,
	`deleted_at`	TIMESTAMP	NULL,
	`read_at`	TIMESTAMP	NULL
);

DROP TABLE IF EXISTS `ANSWER_ATTACHMENT`;

CREATE TABLE `ANSWER_ATTACHMENT` (
	`answer_attachment_id`	BIGINT	NOT NULL,
	`answer_id`	BIGINT	NOT NULL,
	`s3_key`	VARCHAR(512)	NULL,
	`file_size`	INT	NULL	COMMENT 'Byte 단위',
	`created_at`	TIMESTAMP	NOT NULL,
	`deleted_at`	TIMESTAMP	NULL
);

DROP TABLE IF EXISTS `APP_SPEED_LIMIT`;

CREATE TABLE `APP_SPEED_LIMIT` (
	`app_speed_limit_id`	BIGINT	NOT NULL,
	`line_id`	BIGINT	NOT NULL,
	`application_id`	INT	NOT NULL,
	`speed_limit`	INT	NOT NULL	COMMENT 'kbps',
	`is_active`	BOOLEAN	NOT NULL,
	`created_at`	TIMESTAMP	NOT NULL,
	`deleted_at`	TIMESTAMP	NULL,
	`updated_at`	TIMESTAMP	NULL
);

DROP TABLE IF EXISTS `POLICY_CATEGORY`;

CREATE TABLE `POLICY_CATEGORY` (
	`policy_category_id`	INT	NOT NULL,
	`policy_category_name`	VARCHAR(20)	NOT NULL,
	`created_at`	TIMESTAMP	NOT NULL,
	`deleted_at`	TIMESTAMP	NULL,
	`updated_at`	TIMESTAMP	NULL
);

DROP TABLE IF EXISTS `SHARED_LIMIT`;

CREATE TABLE `SHARED_LIMIT` (
	`shared_limit_id`	BIGINT	NOT NULL,
	`line_id`	BIGINT	NOT NULL,
	`shared_data_limit`	BIGINT	NOT NULL	COMMENT '단위 - KB',
	`is_active`	BOOLEAN	NOT NULL,
	`created_at`	TIMESTAMP	NOT NULL,
	`deleted_at`	TIMESTAMP	NULL,
	`updated_at`	TIMESTAMP	NULL
);

DROP TABLE IF EXISTS `REPEAT_BLOCK_DAY`;

CREATE TABLE `REPEAT_BLOCK_DAY` (
	`day_of_week`	ENUM('SUN','MON','TUE','WED','THU','FRI','SAT')	NOT NULL,
	`repeat_block_id`	BIGINT	NOT NULL,
	`created_at`	TIMESTAMP	NOT NULL
);

DROP TABLE IF EXISTS `USER_ROLE`;

CREATE TABLE `USER_ROLE` (
	`user_id`	BIGINT	NOT NULL,
	`role_id`	INT	NOT NULL,
	`created_at`	TIMESTAMP	NOT NULL
);

DROP TABLE IF EXISTS `ANSWER`;

CREATE TABLE `ANSWER` (
	`answer_id`	BIGINT	NOT NULL,
	`user_id`	BIGINT	NOT NULL	COMMENT '답변을 작성한 관리자',
	`question_id`	BIGINT	NOT NULL,
	`content`	VARCHAR(2000)	NOT NULL,
	`created_at`	TIMESTAMP	NOT NULL,
	`deleted_at`	TIMESTAMP	NULL
);

DROP TABLE IF EXISTS `QUESTION_ATTACHMENT`;

CREATE TABLE `QUESTION_ATTACHMENT` (
	`question_attachment_id`	BIGINT	NOT NULL,
	`question_id`	BIGINT	NOT NULL,
	`s3_key`	VARCHAR(512)	NOT NULL,
	`file_size`	INT	NOT NULL	COMMENT 'Byte 단위, 사진 제한 크기 설정해두기',
	`created_at`	TIMESTAMP	NOT NULL,
	`deleted_at`	TIMESTAMP	NULL
);

DROP TABLE IF EXISTS `APP_DATA_LIMIT`;

CREATE TABLE `APP_DATA_LIMIT` (
	`app_data_limit_id`	BIGINT	NOT NULL,
	`line_id`	BIGINT	NOT NULL,
	`application_id`	INT	NOT NULL,
	`data_limit`	BIGINT	NOT NULL	COMMENT 'KB',
	`is_active`	BOOLEAN	NOT NULL,
	`created_at`	TIMESTAMP	NOT NULL,
	`deleted_at`	TIMESTAMP	NULL,
	`updated_at`	TIMESTAMP	NULL
);

DROP TABLE IF EXISTS `FAMILY_POLICY`;

CREATE TABLE `FAMILY_POLICY` (
	`family_id`	BIGINT	NOT NULL,
	`policy_id`	INT	NOT NULL,
	`created_at`	TIMESTAMP	NOT NULL
);

DROP TABLE IF EXISTS `PLAN`;

CREATE TABLE `PLAN` (
	`plan_id`	INT	NOT NULL,
	`plan_category`	VARCHAR(20)	NOT NULL,
	`plan_name`	VARCHAR(30)	NOT NULL,
	`basic_data_amount`	BIGINT	NOT NULL	COMMENT '무제한일 경우 0',
	`shared_pool_amount`	BIGINT	NOT NULL,
	`network_type`	ENUM('LTE', '5G')	NOT NULL,
	`qos_speed_limit`	INT	NOT NULL	COMMENT '단위 - KB, 무제한, 종량제 요금의 경우 0',
	`is_unlimited`	BOOLEAN	NOT NULL,
	`created_at`	TIMESTAMP	NOT NULL,
	`deleted_at`	TIMESTAMP	NULL,
	`updated_at`	TIMESTAMP	NULL
);

DROP TABLE IF EXISTS `ALARM_SETTING`;

CREATE TABLE `ALARM_SETTING` (
	`user_id`	BIGINT	NOT NULL,
	`family_alarm`	BOOLEAN	NOT NULL	DEFAULT TRUE,
	`user_alarm`	BOOLEAN	NOT NULL	DEFAULT TRUE,
	`policy_change_alarm`	BOOLEAN	NOT NULL	DEFAULT TRUE,
	`policy_limit_alarm`	BOOLEAN	NOT NULL	DEFAULT TRUE,
	`permission_alarm`	BOOLEAN	NOT NULL	DEFAULT TRUE,
	`question_alarm`	BOOLEAN	NOT NULL	DEFAULT TRUE,
	`created_at`	TIMESTAMP	NOT NULL,
	`deleted_at`	TIMESTAMP	NULL,
	`updated_at`	TIMESTAMP	NULL
);

ALTER TABLE `DAILY_APP_TOTAL_DATA` ADD CONSTRAINT `PK_DAILY_APP_TOTAL_DATA` PRIMARY KEY (
	`usage_date`,
	`line_id`,
	`application_id`
);

ALTER TABLE `QUESTION_CATEGORY` ADD CONSTRAINT `PK_QUESTION_CATEGORY` PRIMARY KEY (
	`question_category_id`
);

ALTER TABLE `WHITELIST` ADD CONSTRAINT `PK_WHITELIST` PRIMARY KEY (
	`whitelist_id`
);

ALTER TABLE `DAILY_LIMIT` ADD CONSTRAINT `PK_DAILY_LIMIT` PRIMARY KEY (
	`daily_limit_id`
);

ALTER TABLE `DAILY_TOTAL_DATA` ADD CONSTRAINT `PK_DAILY_TOTAL_DATA` PRIMARY KEY (
	`usage_date`,
	`line_id`
);

ALTER TABLE `REPEAT_BLOCK` ADD CONSTRAINT `PK_REPEAT_BLOCK` PRIMARY KEY (
	`repeat_block_id`
);

ALTER TABLE `FAMILY` ADD CONSTRAINT `PK_FAMILY` PRIMARY KEY (
	`family_id`
);

ALTER TABLE `PERMISSION` ADD CONSTRAINT `PK_PERMISSION` PRIMARY KEY (
	`permission_id`
);

ALTER TABLE `POLICY` ADD CONSTRAINT `PK_POLICY` PRIMARY KEY (
	`policy_id`
);

ALTER TABLE `FAMILY_SHARED_USAGE_DAILY` ADD CONSTRAINT `PK_FAMILY_SHARED_USAGE_DAILY` PRIMARY KEY (
	`usage_date`,
	`family_id`,
	`line_id`
);

ALTER TABLE `LINE` ADD CONSTRAINT `PK_LINE` PRIMARY KEY (
	`line_id`
);

ALTER TABLE `ROLE` ADD CONSTRAINT `PK_ROLE` PRIMARY KEY (
	`role_id`
);

ALTER TABLE `FAMILY_LINE` ADD CONSTRAINT `PK_FAMILY_LINE` PRIMARY KEY (
	`family_id`,
	`line_id`
);

ALTER TABLE `QUESTION` ADD CONSTRAINT `PK_QUESTION` PRIMARY KEY (
	`question_id`
);

ALTER TABLE `Application` ADD CONSTRAINT `PK_APPLICATION` PRIMARY KEY (
	`application_id`
);

ALTER TABLE `USERS` ADD CONSTRAINT `PK_USERS` PRIMARY KEY (
	`user_id`
);

ALTER TABLE `PERMISSION_LINE` ADD CONSTRAINT `PK_PERMISSION_LINE` PRIMARY KEY (
	`line_id`,
	`permission_id`
);

ALTER TABLE `ALRAM_HISTORY` ADD CONSTRAINT `PK_ALRAM_HISTORY` PRIMARY KEY (
	`alarm_history_id`
);

ALTER TABLE `ANSWER_ATTACHMENT` ADD CONSTRAINT `PK_ANSWER_ATTACHMENT` PRIMARY KEY (
	`answer_attachment_id`
);

ALTER TABLE `APP_SPEED_LIMIT` ADD CONSTRAINT `PK_APP_SPEED_LIMIT` PRIMARY KEY (
	`app_speed_limit_id`
);

ALTER TABLE `POLICY_CATEGORY` ADD CONSTRAINT `PK_POLICY_CATEGORY` PRIMARY KEY (
	`policy_category_id`
);

ALTER TABLE `SHARED_LIMIT` ADD CONSTRAINT `PK_SHARED_LIMIT` PRIMARY KEY (
	`shared_limit_id`
);

ALTER TABLE `REPEAT_BLOCK_DAY` ADD CONSTRAINT `PK_REPEAT_BLOCK_DAY` PRIMARY KEY (
	`day_of_week`,
	`repeat_block_id`
);

ALTER TABLE `USER_ROLE` ADD CONSTRAINT `PK_USER_ROLE` PRIMARY KEY (
	`user_id`,
	`role_id`
);

ALTER TABLE `ANSWER` ADD CONSTRAINT `PK_ANSWER` PRIMARY KEY (
	`answer_id`
);

ALTER TABLE `QUESTION_ATTACHMENT` ADD CONSTRAINT `PK_QUESTION_ATTACHMENT` PRIMARY KEY (
	`question_attachment_id`
);

ALTER TABLE `APP_DATA_LIMIT` ADD CONSTRAINT `PK_APP_DATA_LIMIT` PRIMARY KEY (
	`app_data_limit_id`
);

ALTER TABLE `FAMILY_POLICY` ADD CONSTRAINT `PK_FAMILY_POLICY` PRIMARY KEY (
	`family_id`,
	`policy_id`
);

ALTER TABLE `PLAN` ADD CONSTRAINT `PK_PLAN` PRIMARY KEY (
	`plan_id`
);

ALTER TABLE `ALARM_SETTING` ADD CONSTRAINT `PK_ALARM_SETTING` PRIMARY KEY (
	`user_id`
);

ALTER TABLE `DAILY_APP_TOTAL_DATA` ADD CONSTRAINT `FK_LINE_TO_DAILY_APP_TOTAL_DATA_1` FOREIGN KEY (
	`line_id`
)
REFERENCES `LINE` (
	`line_id`
);

ALTER TABLE `DAILY_APP_TOTAL_DATA` ADD CONSTRAINT `FK_Application_TO_DAILY_APP_TOTAL_DATA_1` FOREIGN KEY (
	`application_id`
)
REFERENCES `Application` (
	`application_id`
);

ALTER TABLE `WHITELIST` ADD CONSTRAINT `FK_LINE_TO_WHITELIST_1` FOREIGN KEY (
	`line_id`
)
REFERENCES `LINE` (
	`line_id`
);

ALTER TABLE `WHITELIST` ADD CONSTRAINT `FK_Application_TO_WHITELIST_1` FOREIGN KEY (
	`application_id`
)
REFERENCES `Application` (
	`application_id`
);

ALTER TABLE `DAILY_LIMIT` ADD CONSTRAINT `FK_LINE_TO_DAILY_LIMIT_1` FOREIGN KEY (
	`line_id`
)
REFERENCES `LINE` (
	`line_id`
);

ALTER TABLE `DAILY_TOTAL_DATA` ADD CONSTRAINT `FK_LINE_TO_DAILY_TOTAL_DATA_1` FOREIGN KEY (
	`line_id`
)
REFERENCES `LINE` (
	`line_id`
);

ALTER TABLE `REPEAT_BLOCK` ADD CONSTRAINT `FK_LINE_TO_REPEAT_BLOCK_1` FOREIGN KEY (
	`line_id`
)
REFERENCES `LINE` (
	`line_id`
);

ALTER TABLE `POLICY` ADD CONSTRAINT `FK_POLICY_CATEGORY_TO_POLICY_1` FOREIGN KEY (
	`policy_category_id`
)
REFERENCES `POLICY_CATEGORY` (
	`policy_category_id`
);

ALTER TABLE `FAMILY_SHARED_USAGE_DAILY` ADD CONSTRAINT `FK_FAMILY_TO_FAMILY_SHARED_USAGE_DAILY_1` FOREIGN KEY (
	`family_id`
)
REFERENCES `FAMILY` (
	`family_id`
);

ALTER TABLE `FAMILY_SHARED_USAGE_DAILY` ADD CONSTRAINT `FK_LINE_TO_FAMILY_SHARED_USAGE_DAILY_1` FOREIGN KEY (
	`line_id`
)
REFERENCES `LINE` (
	`line_id`
);

ALTER TABLE `LINE` ADD CONSTRAINT `FK_USERS_TO_LINE_1` FOREIGN KEY (
	`user_id`
)
REFERENCES `USERS` (
	`user_id`
);

ALTER TABLE `LINE` ADD CONSTRAINT `FK_PLAN_TO_LINE_1` FOREIGN KEY (
	`plan_id`
)
REFERENCES `PLAN` (
	`plan_id`
);

ALTER TABLE `FAMILY_LINE` ADD CONSTRAINT `FK_FAMILY_TO_FAMILY_LINE_1` FOREIGN KEY (
	`family_id`
)
REFERENCES `FAMILY` (
	`family_id`
);

ALTER TABLE `FAMILY_LINE` ADD CONSTRAINT `FK_LINE_TO_FAMILY_LINE_1` FOREIGN KEY (
	`line_id`
)
REFERENCES `LINE` (
	`line_id`
);

ALTER TABLE `QUESTION` ADD CONSTRAINT `FK_QUESTION_CATEGORY_TO_QUESTION_1` FOREIGN KEY (
	`question_category_id`
)
REFERENCES `QUESTION_CATEGORY` (
	`question_category_id`
);

ALTER TABLE `QUESTION` ADD CONSTRAINT `FK_LINE_TO_QUESTION_1` FOREIGN KEY (
	`line_id`
)
REFERENCES `LINE` (
	`line_id`
);

ALTER TABLE `PERMISSION_LINE` ADD CONSTRAINT `FK_LINE_TO_PERMISSION_LINE_1` FOREIGN KEY (
	`line_id`
)
REFERENCES `LINE` (
	`line_id`
);

ALTER TABLE `PERMISSION_LINE` ADD CONSTRAINT `FK_PERMISSION_TO_PERMISSION_LINE_1` FOREIGN KEY (
	`permission_id`
)
REFERENCES `PERMISSION` (
	`permission_id`
);

ALTER TABLE `ALRAM_HISTORY` ADD CONSTRAINT `FK_USERS_TO_ALRAM_HISTORY_1` FOREIGN KEY (
	`user_id`
)
REFERENCES `USERS` (
	`user_id`
);

ALTER TABLE `ANSWER_ATTACHMENT` ADD CONSTRAINT `FK_ANSWER_TO_ANSWER_ATTACHMENT_1` FOREIGN KEY (
	`answer_id`
)
REFERENCES `ANSWER` (
	`answer_id`
);

ALTER TABLE `APP_SPEED_LIMIT` ADD CONSTRAINT `FK_LINE_TO_APP_SPEED_LIMIT_1` FOREIGN KEY (
	`line_id`
)
REFERENCES `LINE` (
	`line_id`
);

ALTER TABLE `APP_SPEED_LIMIT` ADD CONSTRAINT `FK_Application_TO_APP_SPEED_LIMIT_1` FOREIGN KEY (
	`application_id`
)
REFERENCES `Application` (
	`application_id`
);

ALTER TABLE `SHARED_LIMIT` ADD CONSTRAINT `FK_LINE_TO_SHARED_LIMIT_1` FOREIGN KEY (
	`line_id`
)
REFERENCES `LINE` (
	`line_id`
);

ALTER TABLE `REPEAT_BLOCK_DAY` ADD CONSTRAINT `FK_REPEAT_BLOCK_TO_REPEAT_BLOCK_DAY_1` FOREIGN KEY (
	`repeat_block_id`
)
REFERENCES `REPEAT_BLOCK` (
	`repeat_block_id`
);

ALTER TABLE `USER_ROLE` ADD CONSTRAINT `FK_USERS_TO_USER_ROLE_1` FOREIGN KEY (
	`user_id`
)
REFERENCES `USERS` (
	`user_id`
);

ALTER TABLE `USER_ROLE` ADD CONSTRAINT `FK_ROLE_TO_USER_ROLE_1` FOREIGN KEY (
	`role_id`
)
REFERENCES `ROLE` (
	`role_id`
);

ALTER TABLE `ANSWER` ADD CONSTRAINT `FK_USERS_TO_ANSWER_1` FOREIGN KEY (
	`user_id`
)
REFERENCES `USERS` (
	`user_id`
);

ALTER TABLE `ANSWER` ADD CONSTRAINT `FK_QUESTION_TO_ANSWER_1` FOREIGN KEY (
	`question_id`
)
REFERENCES `QUESTION` (
	`question_id`
);

ALTER TABLE `QUESTION_ATTACHMENT` ADD CONSTRAINT `FK_QUESTION_TO_QUESTION_ATTACHMENT_1` FOREIGN KEY (
	`question_id`
)
REFERENCES `QUESTION` (
	`question_id`
);

ALTER TABLE `APP_DATA_LIMIT` ADD CONSTRAINT `FK_LINE_TO_APP_DATA_LIMIT_1` FOREIGN KEY (
	`line_id`
)
REFERENCES `LINE` (
	`line_id`
);

ALTER TABLE `APP_DATA_LIMIT` ADD CONSTRAINT `FK_Application_TO_APP_DATA_LIMIT_1` FOREIGN KEY (
	`application_id`
)
REFERENCES `Application` (
	`application_id`
);

ALTER TABLE `FAMILY_POLICY` ADD CONSTRAINT `FK_FAMILY_TO_FAMILY_POLICY_1` FOREIGN KEY (
	`family_id`
)
REFERENCES `FAMILY` (
	`family_id`
);

ALTER TABLE `FAMILY_POLICY` ADD CONSTRAINT `FK_POLICY_TO_FAMILY_POLICY_1` FOREIGN KEY (
	`policy_id`
)
REFERENCES `POLICY` (
	`policy_id`
);

ALTER TABLE `ALARM_SETTING` ADD CONSTRAINT `FK_USERS_TO_ALARM_SETTING_1` FOREIGN KEY (
	`user_id`
)
REFERENCES `USERS` (
	`user_id`
);

