-- 1. 외래 키 제약 조건 체크 해제
SET FOREIGN_KEY_CHECKS = 0;

-- 1. ALRAM_HISTORY 테이블
ALTER TABLE `ALRAM_HISTORY` MODIFY COLUMN `alarm_history_id` bigint NOT NULL AUTO_INCREMENT;

-- 2. ANSWER 테이블
ALTER TABLE `ANSWER` MODIFY COLUMN `answer_id` bigint NOT NULL AUTO_INCREMENT;

-- 3. ANSWER_ATTACHMENT 테이블
ALTER TABLE `ANSWER_ATTACHMENT` MODIFY COLUMN `answer_attachment_id` bigint NOT NULL AUTO_INCREMENT;

-- 4. APP_POLICY 테이블
ALTER TABLE `APP_POLICY` MODIFY COLUMN `app_policy_id` bigint NOT NULL AUTO_INCREMENT;

-- 5. APPLICATION 테이블
ALTER TABLE `APPLICATION` MODIFY COLUMN `application_id` int NOT NULL AUTO_INCREMENT;

-- 6. DAILY_LIMIT 테이블
ALTER TABLE `DAILY_LIMIT` MODIFY COLUMN `daily_limit_id` bigint NOT NULL AUTO_INCREMENT;

-- 7. FAMILY 테이블
ALTER TABLE `FAMILY` MODIFY COLUMN `family_id` bigint NOT NULL AUTO_INCREMENT;

-- 8. LINE 테이블
ALTER TABLE `LINE` MODIFY COLUMN `line_id` bigint NOT NULL AUTO_INCREMENT;

-- 9. PERMISSION 테이블
ALTER TABLE `PERMISSION` MODIFY COLUMN `permission_id` int NOT NULL AUTO_INCREMENT;

-- 10. PLAN 테이블
ALTER TABLE `PLAN` MODIFY COLUMN `plan_id` int NOT NULL AUTO_INCREMENT;

-- 11. POLICY 테이블
ALTER TABLE `POLICY` MODIFY COLUMN `policy_id` int NOT NULL AUTO_INCREMENT;

-- 12. POLICY_CATEGORY 테이블
ALTER TABLE `POLICY_CATEGORY` MODIFY COLUMN `policy_category_id` int NOT NULL AUTO_INCREMENT;

-- 13. QUESTION 테이블
ALTER TABLE `QUESTION` MODIFY COLUMN `question_id` bigint NOT NULL AUTO_INCREMENT;

-- 14. QUESTION_ATTACHMENT 테이블
ALTER TABLE `QUESTION_ATTACHMENT` MODIFY COLUMN `question_attachment_id` bigint NOT NULL AUTO_INCREMENT;

-- 15. QUESTION_CATEGORY 테이블
ALTER TABLE `QUESTION_CATEGORY` MODIFY COLUMN `question_category_id` int NOT NULL AUTO_INCREMENT;

-- 16. ROLE 테이블
ALTER TABLE `ROLE` MODIFY COLUMN `role_id` int NOT NULL AUTO_INCREMENT;

-- 17. SHARED_LIMIT 테이블
ALTER TABLE `SHARED_LIMIT` MODIFY COLUMN `shared_limit_id` bigint NOT NULL AUTO_INCREMENT;

-- 18. USERS 테이블
ALTER TABLE `USERS` MODIFY COLUMN `user_id` bigint NOT NULL AUTO_INCREMENT;

-- 19. WHITELIST 테이블
ALTER TABLE `WHITELIST` MODIFY COLUMN `whitelist_id` bigint NOT NULL AUTO_INCREMENT;

-- 2. 외래 키 제약 조건 체크 다시 활성화
SET FOREIGN_KEY_CHECKS = 1;