-- 1. LINE_LIMIT: 회선당 1개의 제한 정책 보장
ALTER TABLE `LINE_LIMIT` ADD CONSTRAINT `UQ_LINE_LIMIT_LINE_ID` UNIQUE (`line_id`);

-- 2. APP_POLICY: 회선+앱당 1개의 정책 보장
ALTER TABLE `APP_POLICY` ADD CONSTRAINT `UQ_APP_POLICY_LINE_APP` UNIQUE (`line_id`, `application_id`);

-- 3. V2603031225 마이그레이션에서 누락된 FOREIGN_KEY_CHECKS 복구
SET FOREIGN_KEY_CHECKS = 1;
